name: mobsfscan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --config ./.mobsf'